'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Lightbulb, Sparkles, ArrowRight, TrendingUp, ShieldAlert, CheckCircle2, Zap } from 'lucide-react';

interface InsightItem {
  id: string;
  category: string;
  title: string;
  description: string;
  impact: string;
  actionLabel: string;
  actionHref: string;
  type: 'growth' | 'efficiency' | 'integration' | 'attention';
}

export default function InsightPage() {
  const [insights, setInsights] = useState<InsightItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/insight')
      .then((res) => res.json())
      .then((data) => setInsights(data.insights || []))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-12">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-serif font-bold text-heading">AI Business Insights</h1>
          <p className="text-slate-500 text-sm mt-1">
            Automated recommendations generated by analyzing your conversations, AI employees, and channel trends.
          </p>
        </div>

        <div className="flex items-center space-x-2 px-3 py-1.5 bg-amber-500/10 text-amber-700 rounded-full border border-amber-500/20 text-xs font-bold">
          <Sparkles className="w-4 h-4 text-amber-600" />
          <span>Rule-based from live SQL</span>
        </div>
      </div>

      {/* Insights Cards List */}
      {loading ? (
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-36 bg-cream-200/50 rounded-3xl animate-pulse border border-cream-300" />
          ))}
        </div>
      ) : (
        <div className="space-y-6">
          {insights.length === 0 ? (
            <p className="text-sm text-slate-500">No insights yet — this page only shows facts from your org&apos;s live tables.</p>
          ) : null}
          {insights.map((item) => (
            <div
              key={item.id}
              className="bg-white border border-cream-300 rounded-3xl p-6 shadow-sm hover:shadow-md transition-all flex items-center justify-between space-x-6"
            >
              <div className="flex items-start space-x-4">
                <div
                  className={`p-3.5 rounded-2xl shrink-0 ${
                    item.type === 'growth'
                      ? 'bg-emerald-500/10 text-emerald-600 border border-emerald-500/20'
                      : item.type === 'efficiency'
                      ? 'bg-amber-500/10 text-amber-600 border border-amber-500/20'
                      : item.type === 'attention'
                      ? 'bg-red-500/10 text-red-600 border border-red-500/20'
                      : 'bg-blue-500/10 text-blue-600 border border-blue-500/20'
                  }`}
                >
                  {(() => {
                    switch (item.type) {
                      case 'growth':
                        return <TrendingUp className="w-6 h-6" />;
                      case 'efficiency':
                        return <Zap className="w-6 h-6" />;
                      case 'integration':
                        return <Lightbulb className="w-6 h-6" />;
                      case 'attention':
                        return <ShieldAlert className="w-6 h-6" />;
                      default: {
                        const _exhaustive: never = item.type;
                        return _exhaustive;
                      }
                    }
                  })()}
                </div>

                <div className="space-y-2">
                  <div className="flex items-center space-x-3">
                    <span className="text-[11px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-cream-200 text-slate-700">
                      {item.category}
                    </span>
                    <span className="text-xs font-semibold text-emerald-600">Impact: {item.impact}</span>
                  </div>

                  <h3 className="text-lg font-serif font-bold text-heading">{item.title}</h3>
                  <p className="text-xs text-slate-600 max-w-2xl leading-relaxed">{item.description}</p>
                </div>
              </div>

              <Link
                href={item.actionHref}
                className="px-4 py-2.5 bg-amber-500 hover:bg-amber-600 text-heading text-xs font-bold rounded-2xl flex items-center space-x-2 shrink-0 transition-colors shadow-sm"
              >
                <span>{item.actionLabel}</span>
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
