-- Connector defs seed — Wave A/B (WS-14 / C5, C6).
-- Additive. Does not rewrite infra/db/seeds/connector_defs.sql (27 apps).
-- Does not insert org_connectors — a def is not a connection.
-- Connected is Nango-verified; never mark connected from this seed.
-- Apply after 014_connector_registry.sql (pnpm db:seed).
-- File: infra/db/seeds/connector_defs_wave_ab.sql

INSERT INTO connector_defs (
  key, nango_key, name, category, icon, description, auth_mode,
  risk_class, confirm_policy, vertical_tags, mcp_tools,
  extra_connect_fields, extra_test_fields, executor_status, testable,
  scopes, env_vars, webhook_events, operator_hint, sort_order, updated_at
) VALUES
  (
    'microsoft-outlook',
    'microsoft-outlook',
    'Microsoft Outlook',
    'Email',
    'Mail',
    'Outlook mail via Microsoft Graph — list, draft, send',
    'oauth',
    'send',
    'confirm',
    ARRAY['core', 'email', 'microsoft']::text[],
    ARRAY['outlook_list_messages', 'outlook_draft_email', 'outlook_send']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"recipient","label":"Recipient email (optional send)","placeholder":"user@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['offline_access', 'User.Read', 'Mail.Read', 'Mail.ReadWrite', 'Mail.Send']::text[],
    $j$[{"name":"MICROSOFT_CLIENT_ID","desc":"Azure AD app client ID (paste into Nango UI)"},{"name":"MICROSOFT_CLIENT_SECRET","desc":"Azure AD app client secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['message_received']::text[],
    'Paste a real Microsoft OAuth client into Nango UI :3003. Send requires confirm. Disconnected returns setupUrl /connectors.',
    28,
    NOW()
  ),
  (
    'microsoft-calendar',
    'microsoft-calendar',
    'Microsoft Calendar',
    'Calendar',
    'Calendar',
    'Outlook calendar via Microsoft Graph — list events, availability, create',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'calendar', 'microsoft']::text[],
    ARRAY['outlook_calendar_list_events', 'outlook_calendar_create_event', 'outlook_calendar_check_availability']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"title","label":"Event title (optional create)","placeholder":"Darex strategy call","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['offline_access', 'User.Read', 'Calendars.Read', 'Calendars.ReadWrite']::text[],
    $j$[{"name":"MICROSOFT_CLIENT_ID","desc":"Azure AD app client ID (paste into Nango UI)"},{"name":"MICROSOFT_CLIENT_SECRET","desc":"Azure AD app client secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['event_created', 'event_updated']::text[],
    'Same Microsoft OAuth client as Outlook. Connected lists real Graph events; never-configured is notConnected.',
    29,
    NOW()
  ),
  (
    'salesforce',
    'salesforce',
    'Salesforce CRM',
    'CRM',
    'Database',
    'Salesforce contacts and leads (list / create). Wave B P0 CRM.',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'crm']::text[],
    ARRAY['salesforce_list_contacts', 'salesforce_create_contact', 'salesforce_create_lead']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"email","label":"Contact email (optional create)","placeholder":"lead@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['api', 'refresh_token', 'id']::text[],
    $j$[{"name":"SALESFORCE_INSTANCE_URL","desc":"Fallback instance URL if missing on the Nango connection"}]$j$::jsonb,
    ARRAY['lead_created']::text[],
    'Paste Salesforce Connected App credentials into Nango UI. Instance URL comes from the OAuth token payload.',
    30,
    NOW()
  ),
  (
    'docusign',
    'docusign',
    'DocuSign',
    'Documents',
    'FileText',
    'DocuSign envelopes — list, draft, send for signature (confirm class sign)',
    'oauth',
    'sign',
    'confirm',
    ARRAY['core', 'esign', 'realestate']::text[],
    ARRAY['docusign_list_envelopes', 'docusign_create_envelope', 'docusign_send_envelope']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"signerEmail","label":"Signer email","placeholder":"signer@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['signature', 'extended', 'openid']::text[],
    $j$[{"name":"DOCUSIGN_OAUTH_BASE_URL","desc":"account.docusign.com (prod) or account-d.docusign.com (demo)"}]$j$::jsonb,
    ARRAY['document_created']::text[],
    'Send envelope is confirm class sign. Requires a real document payload — Darex will not invent contract contents.',
    31,
    NOW()
  ),
  (
    'maps',
    'google-maps',
    'Google Maps Geocoding',
    'Maps',
    'MapPin',
    'Address geocoding and reverse geocoding via Google Maps Geocoding API',
    'api_key',
    'read',
    'none',
    ARRAY['core', 'realestate', 'maps']::text[],
    ARRAY['maps_geocode', 'maps_reverse_geocode']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"address","label":"Address to geocode","placeholder":"1600 Amphitheatre Parkway, Mountain View","required":false}]$j$::jsonb,
    'live',
    TRUE,
    '{}'::text[],
    $j$[{"name":"GOOGLE_MAPS_API_KEY","desc":"Google Maps Geocoding API key"}]$j$::jsonb,
    '{}'::text[],
    'Public API key in GOOGLE_MAPS_API_KEY. Missing key is notConnected. Invalid key is revoked. ZERO_RESULTS is an honest empty list, never fabricated coordinates.',
    32,
    NOW()
  ),
  (
    'twilio',
    'twilio',
    'Twilio SMS',
    'Messaging',
    'MessageSquare',
    'Outbound SMS via Twilio (BYOK account SID + auth token)',
    'byok',
    'send',
    'confirm',
    ARRAY['core', 'messaging']::text[],
    ARRAY['twilio_send_sms', 'twilio_list_messages']::text[],
    $j$[{"key":"accountSid","label":"Twilio Account SID","placeholder":"ACxxxxxxxx","required":true},{"key":"authToken","label":"Twilio Auth Token","placeholder":"","required":true,"secret":true,"type":"password"},{"key":"fromNumber","label":"From number","placeholder":"+14155552671","required":true}]$j$::jsonb,
    $j$[{"key":"to","label":"Recipient phone (optional send)","placeholder":"+14155552671","required":false},{"key":"text","label":"Message text","placeholder":"Hello from Darex","required":false}]$j$::jsonb,
    'live',
    TRUE,
    '{}'::text[],
    $j$[{"name":"TWILIO_ACCOUNT_SID","desc":"Fallback Account SID if per-org BYOK is empty"},{"name":"TWILIO_AUTH_TOKEN","desc":"Fallback auth token"},{"name":"TWILIO_FROM_NUMBER","desc":"Fallback from number"}]$j$::jsonb,
    ARRAY['message_sent', 'message_status']::text[],
    'Prefer per-org channels.meta keys. Env is fallback only. Send requires confirm. 401 from Twilio is revoked, not success.',
    33,
    NOW()
  ),
  (
    'zoho-crm',
    'zoho-crm',
    'Zoho CRM',
    'CRM',
    'Database',
    'Zoho CRM contacts and leads (list / create). Wave B leftover CRM.',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'crm', 'india']::text[],
    ARRAY['zoho_list_contacts', 'zoho_create_contact', 'zoho_create_lead']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"email","label":"Contact email (optional create)","placeholder":"lead@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['ZohoCRM.modules.contacts.ALL', 'ZohoCRM.modules.leads.ALL', 'ZohoCRM.users.READ']::text[],
    $j$[{"name":"ZOHO_API_DOMAIN","desc":"Fallback API domain (https://www.zohoapis.com or https://www.zohoapis.in) if missing on the Nango token"}]$j$::jsonb,
    ARRAY['lead_created']::text[],
    'Paste Zoho OAuth client into Nango UI :3003 (provider zoho-crm). api_domain comes from the token. Connected list_contacts is the happy path. Disconnected is notConnected + /connectors. No fake CRM rows.',
    34,
    NOW()
  ),
  (
    'leegality',
    'leegality',
    'Leegality',
    'Documents',
    'FileText',
    'Leegality e-sign — list, create, send (confirm class sign). IN Wave B leftover.',
    'byok',
    'sign',
    'confirm',
    ARRAY['core', 'esign', 'realestate', 'india']::text[],
    ARRAY['leegality_list_documents', 'leegality_create_document', 'leegality_send_document']::text[],
    $j$[{"key":"authToken","label":"Leegality Auth Token","placeholder":"","required":true,"secret":true,"type":"password"},{"key":"profileId","label":"Workflow profileId","placeholder":"","required":false},{"key":"apiBaseUrl","label":"API base (optional)","placeholder":"https://app1.leegality.com/api","required":false}]$j$::jsonb,
    $j$[{"key":"signerEmail","label":"Signer email","placeholder":"signer@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    '{}'::text[],
    $j$[{"name":"LEEGALITY_API_TOKEN","desc":"Fallback X-Auth-Token if per-org BYOK is empty"},{"name":"LEEGALITY_API_BASE_URL","desc":"https://app1.leegality.com/api (prod) or sandbox host"},{"name":"LEEGALITY_PROFILE_ID","desc":"Default workflow profileId for create/send"}]$j$::jsonb,
    ARRAY['document_created']::text[],
    'BYOK: paste Auth Token from the Leegality dashboard into /connectors (or LEEGALITY_API_TOKEN). Send is confirm class sign. Requires a real document + profileId — Darex will not invent contract contents. list_documents is the connected happy path. Live token required; no committed secret.',
    35,
    NOW()
  ),
  (
    'quickbooks',
    'quickbooks',
    'QuickBooks',
    'Finance',
    'Receipt',
    'QuickBooks customers and invoices (list / create customer). Wave B leftover accounting.',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'finance', 'accounting']::text[],
    ARRAY['quickbooks_list_customers', 'quickbooks_create_customer', 'quickbooks_list_invoices']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"email","label":"Customer email (optional create)","placeholder":"billing@example.com","required":false,"type":"email"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['com.intuit.quickbooks.accounting']::text[],
    $j$[{"name":"QUICKBOOKS_API_BASE_URL","desc":"Override API host (default production quickbooks.api.intuit.com)"},{"name":"QUICKBOOKS_ENVIRONMENT","desc":"Set to sandbox to use sandbox-quickbooks.api.intuit.com"},{"name":"QUICKBOOKS_REALM_ID","desc":"Fallback company realmId if missing on the Nango connection"}]$j$::jsonb,
    ARRAY['invoice_created']::text[],
    'Paste Intuit OAuth client into Nango UI :3003 (provider quickbooks). realmId comes from the OAuth connection. Connected list_customers is the happy path. Disconnected is notConnected + /connectors. Never invents invoices or customers.',
    36,
    NOW()
  )
ON CONFLICT (key) DO UPDATE SET
  nango_key = EXCLUDED.nango_key,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  auth_mode = EXCLUDED.auth_mode,
  risk_class = EXCLUDED.risk_class,
  confirm_policy = EXCLUDED.confirm_policy,
  vertical_tags = EXCLUDED.vertical_tags,
  mcp_tools = EXCLUDED.mcp_tools,
  extra_connect_fields = EXCLUDED.extra_connect_fields,
  extra_test_fields = EXCLUDED.extra_test_fields,
  executor_status = EXCLUDED.executor_status,
  testable = EXCLUDED.testable,
  scopes = EXCLUDED.scopes,
  env_vars = EXCLUDED.env_vars,
  webhook_events = EXCLUDED.webhook_events,
  operator_hint = EXCLUDED.operator_hint,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
