-- Connector defs seed — today's 27 catalog apps + risk classes (WS-07 / C3).
-- Source: apps/dashboard/lib/integrations-catalog.ts (fallback seed SOURCE).
-- Risk classes from docs/future-scope/06-integrations-catalog.md §1.
-- Idempotent. Does not insert org_connectors — a def is not a connection.
-- Apply after 014_connector_registry.sql (pnpm db:seed).
-- File: infra/db/seeds/connector_defs.sql

INSERT INTO connector_defs (
  key, nango_key, name, category, icon, description, auth_mode,
  risk_class, confirm_policy, vertical_tags, mcp_tools,
  extra_connect_fields, extra_test_fields, executor_status, testable,
  scopes, env_vars, webhook_events, operator_hint, sort_order, updated_at
) VALUES
  -- 1. whatsapp risk=send
  (
    'whatsapp',
    'whatsapp',
    'WhatsApp Business',
    'Messaging',
    'MessageSquare',
    'Meta Cloud API for inbound & outbound WhatsApp customer messaging',
    'byok',
    'send',
    'confirm',
    ARRAY['core', 'messaging']::text[],
    ARRAY['whatsapp_send']::text[],
    $j$[{"key":"accessToken","label":"System User Access Token","placeholder":"EAAG...","required":true,"secret":true,"type":"password"},{"key":"phoneNumberId","label":"Phone Number ID","placeholder":"1045...","required":true},{"key":"wabaId","label":"WhatsApp Business Account ID (optional)","placeholder":"109...","required":false}]$j$::jsonb,
    $j$[{"key":"recipient","label":"Recipient phone (optional send)","placeholder":"+14155552671","required":false},{"key":"text","label":"Message text (optional send)","placeholder":"Hello from Darex","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['whatsapp_business_messaging', 'whatsapp_business_management']::text[],
    $j$[{"name":"META_ACCESS_TOKEN","desc":"Fallback env token if per-org BYOK is empty (agent path)"},{"name":"WHATSAPP_PHONE_NUMBER_ID","desc":"Fallback phone number id"}]$j$::jsonb,
    ARRAY['messages', 'message_template_status_update']::text[],
    'Paste a Meta system-user token. Connect is verified against Graph before status becomes Connected. Outbound 401 means rotate the token.',
    1,
    NOW()
  ),
  -- 2. gmail risk=send
  (
    'gmail',
    'gmail',
    'Gmail / Email',
    'Email',
    'Mail',
    'Inbound email triage & outbound response drafting via Gmail API',
    'oauth',
    'send',
    'confirm',
    ARRAY['core', 'email']::text[],
    ARRAY['gmail_fetch', 'gmail_send', 'gmail_triage', 'gmail_extract_otp', 'gmail_extract_attachment', 'gmail_draft_email']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"recipient","label":"Recipient email (optional send)","placeholder":"user@example.com","required":false,"type":"email"},{"key":"text","label":"Email content (optional send)","placeholder":"Hello from Darex","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.compose', 'https://www.googleapis.com/auth/gmail.modify']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['message_received']::text[],
    NULL,
    2,
    NOW()
  ),
  -- 3. google-calendar risk=write_sor
  (
    'google-calendar',
    'google-calendar',
    'Google Calendar',
    'Calendar',
    'Calendar',
    'Real-time slot checking & appointment booking',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'calendar']::text[],
    ARRAY['calendar_list_events', 'calendar_create_event', 'calendar_check_availability']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"title","label":"Event title (optional create)","placeholder":"Darex strategy call","required":false},{"key":"attendeesStr","label":"Attendee emails, comma separated","placeholder":"lead@example.com","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/calendar.events']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['event_created', 'event_updated']::text[],
    NULL,
    3,
    NOW()
  ),
  -- 4. google-ads risk=publish
  (
    'google-ads',
    'google-ads',
    'Google Ads',
    'Advertising',
    'BarChart2',
    'Search campaign analytics, conversion logging & ROAS metrics',
    'oauth',
    'publish',
    'confirm',
    ARRAY['core', 'ads']::text[],
    ARRAY['google_ads_metrics']::text[],
    $j$[{"key":"customerId","label":"Google Ads customer ID (optional, stored on the org)","placeholder":"123-456-7890","required":false}]$j$::jsonb,
    $j$[{"key":"customerId","label":"Google Ads customer ID","placeholder":"123-456-7890","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/adwords']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"},{"name":"GOOGLE_ADS_DEVELOPER_TOKEN","desc":"Google Ads API developer token"}]$j$::jsonb,
    ARRAY['conversion_recorded']::text[],
    'Needs a real Google OAuth client in Nango plus GOOGLE_ADS_DEVELOPER_TOKEN for metrics.',
    4,
    NOW()
  ),
  -- 5. meta-ads risk=publish
  (
    'meta-ads',
    'meta-ads',
    'Meta Ads',
    'Advertising',
    'Megaphone',
    'ROAS tracking & Meta ad campaign performance monitoring',
    'oauth',
    'publish',
    'confirm',
    ARRAY['core', 'ads']::text[],
    ARRAY['meta_ads_metrics']::text[],
    $j$[{"key":"adAccountId","label":"Meta ad account ID (optional)","placeholder":"act_123456789","required":false}]$j$::jsonb,
    $j$[{"key":"adAccountId","label":"Meta ad account ID","placeholder":"act_123456789","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['ads_management', 'ads_read']::text[],
    $j$[{"name":"META_APP_ID","desc":"Meta App ID (paste into Nango UI)"},{"name":"META_APP_SECRET","desc":"Meta App Secret (paste into Nango UI)"},{"name":"META_AD_ACCOUNT_ID","desc":"Fallback ad account id"}]$j$::jsonb,
    ARRAY['leadgen']::text[],
    'Paste a real Meta OAuth client ID/secret into the Nango UI at :3003 before the popup can finish.',
    5,
    NOW()
  ),
  -- 6. hubspot risk=write_sor
  (
    'hubspot',
    'hubspot',
    'HubSpot CRM',
    'CRM',
    'Database',
    'Automatic contact creation, deal stage updates & lead tracking',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'crm']::text[],
    ARRAY['hubspot_create_contact', 'hubspot_update_contact']::text[],
    $j$[]$j$::jsonb,
    $j$[{"key":"email","label":"Contact email (optional create)","placeholder":"lead@example.com","required":false,"type":"email"},{"key":"firstName","label":"First name","placeholder":"Alex","required":false},{"key":"lastName","label":"Last name","placeholder":"Morgan","required":false}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['crm.objects.contacts.read', 'crm.objects.contacts.write']::text[],
    $j$[{"name":"HUBSPOT_CLIENT_ID","desc":"HubSpot app client ID (paste into Nango UI)"},{"name":"HUBSPOT_CLIENT_SECRET","desc":"HubSpot app client secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['contact.creation']::text[],
    'Needs a real HubSpot OAuth client ID in the Nango UI.',
    6,
    NOW()
  ),
  -- 7. stripe risk=pay
  (
    'stripe',
    'stripe',
    'Stripe Payments',
    'Payments',
    'CreditCard',
    'Subscription tracking, payment links & customer billing sync',
    'oauth',
    'pay',
    'confirm',
    ARRAY['core', 'payments']::text[],
    ARRAY['stripe_create_payment_link', 'stripe_create_customer', 'stripe_get_customer']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['read_write']::text[],
    $j$[{"name":"STRIPE_CLIENT_ID","desc":"Stripe Connect client ID (paste into Nango UI)"},{"name":"STRIPE_SECRET_KEY","desc":"Not stored here — Nango holds the connected account token"}]$j$::jsonb,
    ARRAY['payment_intent.succeeded']::text[],
    'Needs a real Stripe OAuth client ID in the Nango UI.',
    7,
    NOW()
  ),
  -- 8. notion risk=write_sor
  (
    'notion',
    'notion',
    'Notion Workspace',
    'Knowledge',
    'BookOpen',
    'Sync knowledge bases, product docs & team task databases',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'knowledge']::text[],
    ARRAY['notion_create_page', 'notion_append_page_content', 'notion_search']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['read', 'write']::text[],
    $j$[{"name":"NOTION_CLIENT_ID","desc":"Notion integration client ID (paste into Nango UI)"},{"name":"NOTION_CLIENT_SECRET","desc":"Notion integration secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['page.created']::text[],
    'Needs a real Notion OAuth client ID in the Nango UI.',
    8,
    NOW()
  ),
  -- 9. slack risk=send
  (
    'slack',
    'slack',
    'Slack Notifications',
    'Messaging',
    'Slack',
    'Team alerts, channel notifications & human-handoff triggers',
    'oauth',
    'send',
    'confirm',
    ARRAY['core', 'messaging']::text[],
    ARRAY['slack_send']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['chat:write', 'channels:read', 'users:read']::text[],
    $j$[{"name":"SLACK_CLIENT_ID","desc":"Slack app client ID (paste into Nango UI)"},{"name":"SLACK_CLIENT_SECRET","desc":"Slack app client secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['message.channels']::text[],
    'Needs a real Slack OAuth client ID in the Nango UI.',
    9,
    NOW()
  ),
  -- 10. shopify risk=write_sor
  (
    'shopify',
    'shopify',
    'Shopify Store',
    'E-Commerce',
    'ShoppingBag',
    'Order tracking, inventory queries & customer fulfillment sync',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'ecommerce']::text[],
    ARRAY['shopify_fetch_products', 'shopify_fetch_orders']::text[],
    $j$[{"key":"shopDomain","label":"Shop domain","placeholder":"my-store.myshopify.com","required":true}]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['read_products', 'read_orders', 'write_orders']::text[],
    $j$[{"name":"SHOPIFY_CLIENT_ID","desc":"Shopify app client ID (paste into Nango UI)"},{"name":"SHOPIFY_CLIENT_SECRET","desc":"Shopify app secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['orders/create']::text[],
    'Needs a real Shopify OAuth client in Nango plus the shop subdomain for the popup.',
    10,
    NOW()
  ),
  -- 11. zendesk risk=write_sor
  (
    'zendesk',
    'zendesk',
    'Zendesk Support',
    'Support',
    'Headphones',
    'Helpdesk ticket creation & customer escalation sync',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'support']::text[],
    ARRAY['zendesk_fetch_tickets', 'zendesk_create_ticket', 'zendesk_update_ticket']::text[],
    $j$[{"key":"subdomain","label":"Zendesk subdomain","placeholder":"mycompany","required":true}]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['read', 'write']::text[],
    $j$[{"name":"ZENDESK_CLIENT_ID","desc":"Zendesk OAuth client ID (paste into Nango UI)"},{"name":"ZENDESK_CLIENT_SECRET","desc":"Zendesk OAuth secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['ticket.created']::text[],
    'Needs a real Zendesk OAuth client in Nango plus the account subdomain.',
    11,
    NOW()
  ),
  -- 12. intercom risk=send
  (
    'intercom',
    'intercom',
    'Intercom Inbox',
    'Support',
    'MessageCircle',
    'Live customer chat sync & agent assignment',
    'oauth',
    'send',
    'confirm',
    ARRAY['core', 'support']::text[],
    ARRAY['intercom_fetch_conversations', 'intercom_reply', 'intercom_create_conversation']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['read', 'write']::text[],
    $j$[{"name":"INTERCOM_CLIENT_ID","desc":"Intercom app client ID (paste into Nango UI)"},{"name":"INTERCOM_CLIENT_SECRET","desc":"Intercom app secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['conversation.created']::text[],
    'Needs a real Intercom OAuth client ID in the Nango UI. Agent tools: fetch, reply, create conversation.',
    12,
    NOW()
  ),
  -- 13. github risk=write_sor
  (
    'github',
    'github',
    'GitHub Code',
    'Development',
    'Github',
    'Repository sync, pull request logs & issue tracking',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'development']::text[],
    ARRAY['github_fetch_repos', 'github_create_repo', 'github_create_issue']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['repo', 'read:org']::text[],
    $j$[{"name":"GITHUB_CLIENT_ID","desc":"GitHub OAuth app client ID (paste into Nango UI)"},{"name":"GITHUB_CLIENT_SECRET","desc":"GitHub OAuth app secret (paste into Nango UI)"}]$j$::jsonb,
    ARRAY['issues', 'pull_request']::text[],
    NULL,
    13,
    NOW()
  ),
  -- 14. razorpay risk=pay
  (
    'razorpay',
    'razorpay',
    'Razorpay Invoices',
    'Payments',
    'CreditCard',
    'Instant payment link generation & invoice status queries',
    'api_key',
    'pay',
    'confirm',
    ARRAY['core', 'payments']::text[],
    ARRAY['razorpay_create_payment_link']::text[],
    $j$[{"key":"keyId","label":"Key ID","placeholder":"rzp_live_...","required":true},{"key":"keySecret","label":"Key Secret","placeholder":"••••","required":true,"secret":true,"type":"password"}]$j$::jsonb,
    $j$[{"key":"customerEmail","label":"Customer email (optional invoice)","placeholder":"billing@example.com","required":false,"type":"email"},{"key":"amountInPaisa","label":"Amount in paisa (optional invoice)","placeholder":"499900","required":false,"type":"number"}]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['invoices.write', 'payments.read']::text[],
    $j$[{"name":"RAZORPAY_KEY_ID","desc":"Fallback env key used by the agent if per-org keys are empty"},{"name":"RAZORPAY_KEY_SECRET","desc":"Fallback env secret"}]$j$::jsonb,
    ARRAY['payment.authorized']::text[],
    'Not Nango OAuth. Per-org keys are verified into channels.meta; agent tools use those first, then RAZORPAY_KEY_ID/SECRET env.',
    14,
    NOW()
  ),
  -- 15. google-drive risk=write_sor
  (
    'google-drive',
    'google-drive',
    'Google Drive',
    'Productivity',
    'FolderOpen',
    'Search, read, upload & share files across Google Drive',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'productivity']::text[],
    ARRAY['drive_search', 'drive_list', 'drive_get_text', 'drive_upload', 'drive_share']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/drive']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    15,
    NOW()
  ),
  -- 16. google-docs risk=write_sor
  (
    'google-docs',
    'google-docs',
    'Google Docs',
    'Productivity',
    'FileText',
    'Create, read & append content in Google Docs documents',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'productivity']::text[],
    ARRAY['docs_create', 'docs_read', 'docs_append']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/documents', 'https://www.googleapis.com/auth/drive']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    16,
    NOW()
  ),
  -- 17. google-sheets risk=write_sor
  (
    'google-sheets',
    'google-sheets',
    'Google Sheets',
    'Productivity',
    'Table',
    'Read, create & append rows in Google Sheets spreadsheets',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'productivity']::text[],
    ARRAY['sheets_create', 'sheets_read', 'sheets_append_row']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    17,
    NOW()
  ),
  -- 18. google-slides risk=publish
  (
    'google-slides',
    'google-slides',
    'Google Slides',
    'Productivity',
    'Presentation',
    'Create & present slide decks in Google Slides',
    'oauth',
    'publish',
    'confirm',
    ARRAY['core', 'productivity']::text[],
    ARRAY['slides_create']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    18,
    NOW()
  ),
  -- 19. google-forms risk=read
  (
    'google-forms',
    'google-forms',
    'Google Forms',
    'Productivity',
    'FileCheck',
    'Read & capture form structure and responses',
    'oauth',
    'read',
    'none',
    ARRAY['core', 'productivity']::text[],
    ARRAY['forms_get']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/forms.body', 'https://www.googleapis.com/auth/forms.responses.readonly']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    19,
    NOW()
  ),
  -- 20. google-chat risk=send
  (
    'google-chat',
    'google-chat',
    'Google Chat',
    'Messaging',
    'MessageSquare',
    'Send & receive messages in Google Chat spaces',
    'oauth',
    'send',
    'confirm',
    ARRAY['core', 'messaging']::text[],
    ARRAY['chat_list_spaces', 'chat_send_message']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/chat.messages', 'https://www.googleapis.com/auth/chat.spaces']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango. Agent tools: chat_list_spaces, chat_send_message.',
    20,
    NOW()
  ),
  -- 21. google-meet risk=write_sor
  (
    'google-meet',
    'google-meet',
    'Google Meet',
    'Meetings',
    'Video',
    'Schedule and manage Google Meet video spaces',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'meetings']::text[],
    ARRAY['meet_create_space', 'meet_get_space']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/meetings.space.created', 'https://www.googleapis.com/auth/meetings.space.readonly']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango. Agent tools: meet_create_space, meet_get_space.',
    21,
    NOW()
  ),
  -- 22. google-contacts risk=write_sor
  (
    'google-contacts',
    'google-contacts',
    'Google Contacts',
    'Contacts',
    'Users',
    'Sync & query organization contacts and directory',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'contacts']::text[],
    ARRAY['contacts_list']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/contacts']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    22,
    NOW()
  ),
  -- 23. google-tasks risk=write_sor
  (
    'google-tasks',
    'google-tasks',
    'Google Tasks',
    'Productivity',
    'CheckSquare',
    'Create and manage task lists in Google Tasks',
    'oauth',
    'write_sor',
    'confirm',
    ARRAY['core', 'productivity']::text[],
    ARRAY['tasks_list']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/tasks']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    NULL,
    23,
    NOW()
  ),
  -- 24. google-analytics risk=read
  (
    'google-analytics',
    'google-analytics',
    'Google Analytics',
    'Analytics',
    'TrendingUp',
    'Fetch web & app property traffic reports and conversions',
    'oauth',
    'read',
    'none',
    ARRAY['core', 'analytics']::text[],
    ARRAY['analytics_report']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/analytics.readonly']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango. Agent tool analytics_report requires a GA4 propertyId.',
    24,
    NOW()
  ),
  -- 25. google-search-console risk=read
  (
    'google-search-console',
    'google-search-console',
    'Google Search Console',
    'SEO',
    'Search',
    'Analyze search performance, sitemaps & URL inspection',
    'oauth',
    'read',
    'none',
    ARRAY['core', 'seo']::text[],
    ARRAY['search_console_sites', 'search_console_query']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/webmasters']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango. Agent tools: search_console_sites, search_console_query.',
    25,
    NOW()
  ),
  -- 26. google-business-profile risk=publish
  (
    'google-business-profile',
    'google-business-profile',
    'Google Business Profile',
    'Marketing',
    'Store',
    'Manage Google business locations, posts & reviews',
    'oauth',
    'publish',
    'confirm',
    ARRAY['core', 'marketing']::text[],
    ARRAY['business_list_locations']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/business.manage']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango. Agent tool: business_list_locations.',
    26,
    NOW()
  ),
  -- 27. google-cloud risk=read
  (
    'google-cloud',
    'google-cloud',
    'Google Cloud Platform',
    'Infrastructure',
    'Cloud',
    'Cloud resources, BigQuery & infrastructure management',
    'oauth',
    'read',
    'none',
    ARRAY['core', 'infrastructure']::text[],
    ARRAY['cloud_list_projects']::text[],
    $j$[]$j$::jsonb,
    $j$[]$j$::jsonb,
    'live',
    TRUE,
    ARRAY['https://www.googleapis.com/auth/cloud-platform']::text[],
    $j$[{"name":"GOOGLE_CLIENT_ID","desc":"Google Cloud Console OAuth Client ID (paste into Nango UI)"},{"name":"GOOGLE_CLIENT_SECRET","desc":"Google Cloud Console OAuth Client Secret (paste into Nango UI)"}]$j$::jsonb,
    '{}'::text[],
    'Needs a real Google OAuth client in Nango with cloud-platform scope. Agent tool: cloud_list_projects.',
    27,
    NOW()
  )
ON CONFLICT (key) DO UPDATE SET
  nango_key = EXCLUDED.nango_key,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  auth_mode = EXCLUDED.auth_mode,
  risk_class = EXCLUDED.risk_class,
  confirm_policy = EXCLUDED.confirm_policy,
  vertical_tags = EXCLUDED.vertical_tags,
  mcp_tools = EXCLUDED.mcp_tools,
  extra_connect_fields = EXCLUDED.extra_connect_fields,
  extra_test_fields = EXCLUDED.extra_test_fields,
  executor_status = EXCLUDED.executor_status,
  testable = EXCLUDED.testable,
  scopes = EXCLUDED.scopes,
  env_vars = EXCLUDED.env_vars,
  webhook_events = EXCLUDED.webhook_events,
  operator_hint = EXCLUDED.operator_hint,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
